# Generated by Django 6.0.6 on 2026-06-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
