# Generated by Django 6.0.6 on 2026-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_caixinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixinha',
            name='nome',
            field=models.CharField(max_length=25),
        ),
    ]
