# Generated by Django 6.0.6 on 2026-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_previsaodespesa_previsaoreceita'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaodespesa',
            name='data',
            field=models.DateField(default='2026-09-11'),
            preserve_default=False,
        ),
    ]
