# Generated by Django 6.0.6 on 2026-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_previsaodespesa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaoreceita',
            name='data',
            field=models.DateField(default='2026-09-11'),
            preserve_default=False,
        ),
    ]
