# Generated by Django 6.0.6 on 2026-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_previsaoreceita_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsaodespesa',
            name='categoria',
            field=models.CharField(default='despesas', max_length=20),
            preserve_default=False,
        ),
    ]
