# Generated by Django 6.0.6 on 2026-09-12 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_previsaodespesa_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previsaoreceita',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('D', 'Despesas'), ('R', 'Receitas')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PrevisaoDespesa',
        ),
        migrations.DeleteModel(
            name='PrevisaoReceita',
        ),
    ]
