# Generated by Django 6.0.6 on 2026-09-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_remove_previsaoreceita_usuario_previsao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='data',
            field=models.CharField(max_length=50),
        ),
    ]
