# Generated by Django 6.0.6 on 2026-09-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_alter_previsao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsao',
            name='ano',
            field=models.IntegerField(default='2026'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previsao',
            name='data',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')]),
        ),
    ]
